<?php
/**
 * ATCSessionsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  VATSIM\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * VATSIM API
 *
 * API for VATSIM. This API only accepts and returns application/json - e-mail api@vatsim.net for troubleshooting
 *
 * OpenAPI spec version: v1
 * Contact: api@vatsim.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.16
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace VATSIM\Client;

/**
 * ATCSessionsTest Class Doc Comment
 *
 * @category    Class
 * @description ATCSessions
 * @package     VATSIM\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ATCSessionsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ATCSessions"
     */
    public function testATCSessions()
    {
    }

    /**
     * Test attribute "connectionId"
     */
    public function testPropertyConnectionId()
    {
    }

    /**
     * Test attribute "start"
     */
    public function testPropertyStart()
    {
    }

    /**
     * Test attribute "end"
     */
    public function testPropertyEnd()
    {
    }

    /**
     * Test attribute "server"
     */
    public function testPropertyServer()
    {
    }

    /**
     * Test attribute "vatsimId"
     */
    public function testPropertyVatsimId()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "rating"
     */
    public function testPropertyRating()
    {
    }

    /**
     * Test attribute "callsign"
     */
    public function testPropertyCallsign()
    {
    }

    /**
     * Test attribute "timesHeldCallsign"
     */
    public function testPropertyTimesHeldCallsign()
    {
    }

    /**
     * Test attribute "minutesOnCallsign"
     */
    public function testPropertyMinutesOnCallsign()
    {
    }

    /**
     * Test attribute "totalMinutesOnCallsign"
     */
    public function testPropertyTotalMinutesOnCallsign()
    {
    }

    /**
     * Test attribute "aircrafttracked"
     */
    public function testPropertyAircrafttracked()
    {
    }

    /**
     * Test attribute "aircraftseen"
     */
    public function testPropertyAircraftseen()
    {
    }

    /**
     * Test attribute "flightsamended"
     */
    public function testPropertyFlightsamended()
    {
    }

    /**
     * Test attribute "handoffsinitiated"
     */
    public function testPropertyHandoffsinitiated()
    {
    }

    /**
     * Test attribute "handoffsreceived"
     */
    public function testPropertyHandoffsreceived()
    {
    }

    /**
     * Test attribute "handoffsrefused"
     */
    public function testPropertyHandoffsrefused()
    {
    }

    /**
     * Test attribute "squawksassigned"
     */
    public function testPropertySquawksassigned()
    {
    }

    /**
     * Test attribute "cruisealtsmodified"
     */
    public function testPropertyCruisealtsmodified()
    {
    }

    /**
     * Test attribute "tempaltsmodified"
     */
    public function testPropertyTempaltsmodified()
    {
    }

    /**
     * Test attribute "scratchpadmods"
     */
    public function testPropertyScratchpadmods()
    {
    }
}
