<?php
/**
 * RatingsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  VATSIM\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * VATSIM API
 *
 * API for VATSIM. This API only accepts and returns application/json - e-mail api@vatsim.net for troubleshooting
 *
 * OpenAPI spec version: v1
 * Contact: api@vatsim.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.16
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace VATSIM\Client;

use \VATSIM\Client\Configuration;
use \VATSIM\Client\ApiException;
use \VATSIM\Client\ObjectSerializer;

/**
 * RatingsApiTest Class Doc Comment
 *
 * @category Class
 * @package  VATSIM\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RatingsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for ratingsAddComment
     *
     * Append a comment to the members profile..
     *
     */
    public function testRatingsAddComment()
    {
    }

    /**
     * Test case for ratingsConnectionsRead
     *
     * .
     *
     */
    public function testRatingsConnectionsRead()
    {
    }

    /**
     * Test case for ratingsFlightPlans
     *
     * .
     *
     */
    public function testRatingsFlightPlans()
    {
    }

    /**
     * Test case for ratingsPartialUpdate
     *
     * .
     *
     */
    public function testRatingsPartialUpdate()
    {
    }

    /**
     * Test case for ratingsRatingTimes
     *
     * .
     *
     */
    public function testRatingsRatingTimes()
    {
    }

    /**
     * Test case for ratingsRead
     *
     * .
     *
     */
    public function testRatingsRead()
    {
    }

    /**
     * Test case for ratingsRead_0
     *
     * .
     *
     */
    public function testRatingsRead0()
    {
    }
}
